### ISSUE TITLE
盒模型有哪些属性

### ISSUE THREAD

**Issue by fclvhh** [fclvhh/interview#31]
# 盒子模型属性

- margin
  - 四边是顺时针赋值
  - 也可以单独设置
- 盒模型居中
  - `margin:0 auto;`
- padding

```css
.box {
  	padding:10px;
  	padding:10px20px;/*10px20px10px20px*/
    padding:10px20px30px40px;/*上右下左*/
}
.box {
    padding-top:10px;
    padding-bottom:20px;
    padding-left:30px;
    padding-right:40px;
}
        
```

- border

```css
.box {
    border:1px solid black;/*solid、dashed、dotted*/
    border-radius:4px;
    border-radius:50%;
}
.box {
    border-top:10px solid #ccc;
    border-bottom:5px dashed yellow;
    border-left:10px solid transparent;
    border-right:1px dotted black;
}
```

- width 、height

  - 属性值: 100%   代表着什么?
    - 让自己的content大小等于父元素content的100%
  - 带来的问题
    - 如果自己本身还有 padding 等其他的盒子模型相关的属性
    - 就会造成 
      - 自身的大小 超过父容器盒模型 的 content 的大小
      - 出现很奇怪的布局
  - 父元素宽度 一般都是要设置的
    - 但是高度却不一定 , 因为让子元素撑开嘛
    - 出现了需求的 , 再添加高度

  

- display
题目来自饥人谷
