### ISSUE TITLE
如何清除浮动

### ISSUE THREAD

**Issue by fclvhh** [fclvhh/interview#40]
```css
.clearfix::after {
    content:'';
    display:block;
    clear:both;
}
```
题目来自于饥人谷
